testBook:
	rm -f testBook
	g++ -std=c++23 -I./src -o testBook tests/structures/testBook.cpp src/structures/Book.cpp src/structures/Order.cpp
	./testBook

testOrder:
	rm -f testOrder
	g++ -std=c++23 -I./src -o testOrder tests/structures/testOrder.cpp src/structures/Order.cpp
	./testOrder

